---
title: "Queries in GIFT API"
author: "Pierre Denelle & Patrick Weigelt"
date: "`r Sys.Date()`"
output: 
  html_vignette:
    toc: true
    toc_depth: 2
    number_sections: true
vignette: >
 %\VignetteIndexEntry{Queries in GIFT API}
 %\VignetteEncoding{UTF-8} 
 %\VignetteEngine{knitr::rmarkdown}
editor_options: 
 chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 8)
# Packages --------------------------------------------------------------------
suppressPackageStartupMessages({
  suppressWarnings({
    library("GIFT")
    library("kableExtra") # html table with scroll bar
  })
})

options(tinytex.verbose = TRUE)
```


# 1. Overview

See [Weigelt et al. (2020)]((https://doi.org/10.1111/jbi.13623).

No R chunk.
Just a table with two columns:
queries names
arguments needed/possible for each query

```{r}
# Dependency between R functions and queries

r_query <- data.frame(
  R_function = c("GIFT_checklist_raw()", "GIFT_checklist_conditional()",
                 "GIFT_spatial()", "GIFT_taxonomy()", "GIFT_taxgroup()",
                 "GIFT_no_overlap()", "GIFT_checklist()", "GIFT_env()",
                 "GIFT_shape()"),
  Query = c("lists, taxonomy, checklists", "lists, taxonomy", "", "taxonomy",
            "species, taxonomy", "overlap", "lists, taxonomy",
            "geoentities_env_misc, geoentities_env_raster",
            "only calling geojson"),
  Dependency_GIFT = c(
    "", "", "GIFT_env()", "", "", "",
    "GIFT_checklist_conditional(), GIFT_spatial(), GIFT_checklist_raw(),
    GIFT_no_overlap()",
    "", "")
)

r_query
```

# 2. Queries

List of available queries and their arguments:

```{r, eval = FALSE}
api <- ""
GIFT_version <- "latest"

jsonlite::read_json(paste0(
      api, "index", ifelse(GIFT_version == "beta", "", GIFT_version), 
      ".php?query=checklists&listid=",
      as.numeric(list_ID[i]), "&taxonid=", as.numeric(taxonid),
      "&namesmatched=", as.numeric(namesmatched),
      ifelse(floristic_group == "all",
             "", paste0("&filter=", floristic_group))))

jsonlite::read_json(paste0(
      api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
      ".php?query=geoentities_env_misc&envvar=",
      paste(miscellaneous, collapse = ",")),
      simplifyVector = TRUE)

jsonlite::read_json(paste0(
        api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
        ".php?query=geoentities_env_raster&layername=", rasterlayer[i],
        "&sumstat=", sumstat_collapse[[i]]),
        simplifyVector = TRUE)

paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
       ".php?query=lists")

jsonlite::read_json(paste0(
        api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
        ".php?query=names_matched&genus=", genus, "&epithet=", epithet
      ), simplifyVector = TRUE)

jsonlite::read_json(paste0(
        api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
        ".php?query=names_matched_unique&genus=", genus, "&epithet=", epithet
      ), simplifyVector = TRUE)

paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
       ".php?query=overlap")
jsonlite::read_json(paste0(
    api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
    ".php?query=overlap_misc&layer=", resource), simplifyVector = TRUE)

jsonlite::read_json(paste0(
    api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
    ".php?query=references_citavi"), simplifyVector = TRUE)

jsonlite::read_json(paste0(
    api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
    ".php?query=references"), simplifyVector = TRUE)

jsonlite::read_json(
    paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
           ".php?query=reference_traits"), simplifyVector = TRUE)

jsonlite::read_json(paste0(
    api,"index", ifelse(GIFT_version == "beta", "", GIFT_version),
    ".php?query=regions"), simplifyVector = TRUE)

jsonlite::read_json(paste0(
      api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
      ".php?query=species&startat=", as.integer((i-1)*100000)), 
      simplifyVector = TRUE)

jsonlite::read_json(paste0(
        api, "index", ifelse(GIFT_version == "beta", "", GIFT_version), 
        ".php?query=species_distr&nameid=", as.integer(name_IDs[i])), 
        simplifyVector = TRUE)

jsonlite::read_json(paste0(
      api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
      ".php?query=species_num&taxonid=", tax_group), simplifyVector = TRUE)

paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
       ".php?query=taxonomy")

jsonlite::read_json(
        paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
               ".php?query=traits&traitid=",
               trait_IDs[i], "&biasref=", as.numeric(bias_ref),
               "&biasderiv=", as.numeric(bias_deriv), 
               "&startat=", as.integer((k-1)*10000)),
        simplifyVector = TRUE)

jsonlite::read_json(paste0(
      api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
      ".php?query=traits_cov&traitid=",
      paste(trait_ID, collapse = ","), "&taxonid=", tax_group),
      simplifyVector = TRUE)

jsonlite::read_json(
    paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
           ".php?query=traits_meta"), simplifyVector = TRUE)

jsonlite::read_json(
      paste0(api, "index", ifelse(GIFT_version == "beta", "", GIFT_version),
             ".php?query=traits_raw&traitid=",
             ref_IDs$trait_ID[i], "&deriv=", as.numeric(derived),
             "&biasderiv=", as.numeric(bias_deriv),
             "&refid=", as.numeric(ref_IDs$ref_ID[i])), simplifyVector = TRUE)

jsonlite::read_json(
  "https://gift.uni-goettingen.de/api/index.php?query=versions",
  simplifyVector = TRUE)



st_read(
      paste0("http://gift.uni-goettingen.de/geojson/geojson_smaller", 
             ifelse(GIFT_version == "beta", "", GIFT_version), "/",
             entity_ID[i], ".geojson"), quiet = TRUE)

```

<br>

```{r}
# Query for trait and chunks

# Default value for end is 10000
# https://gift.uni-goettingen.de/api/extended/index.php?query=traits&
# traitid=1.1.1&biasref=1&biasderiv=1&startat=100000&limit=10
```


See https://www.gbif.org/developer/summary
http://api.gbif.org/


\newpage

# 4. References

[Weigelt, P., König, C., & Kreft, H. (2020). GIFT – A Global Inventory of Floras and Traits for macroecology and biogeography. Journal of Biogeography, 47(1), 16–43.](https://doi.org/10.1111/jbi.13623)

\newpage

## 4.2. R packages

